# Generated by Django 5.1 on 2024-08-31 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 31, 18, 15, 10, 183288)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 31, 18, 15, 10, 183288)),
        ),
    ]
