# Generated by Django 5.1 on 2024-09-07 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_total_alter_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 17, 14, 7, 634459), verbose_name=datetime.datetime(2024, 9, 7, 17, 14, 7, 634459)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 7, 17, 14, 7, 634459)),
        ),
    ]
